#!/bin/bash
set -ex

# install mysql tables
sudo mysql -u root asterisk < tables-needed.mysql

# install files
sudo tar xvfz files-needed.tgz -C /
sudo chown -R asterisk. /etc/asterisk/digium_phones /var/www/html/digium_phones

# ask FreePBX to rebuild configuration

sudo /usr/local/sbin/amportal a r

# check generated configuration

#for FILE in configs/*
#do
#	CONFIG="${FILE#*/}"
#	diff configs/$CONFIG /etc/asterisk/$CONFIG || exit 1
#done
diff -r configs/. /etc/asterisk/. | fgrep -v 'Only in'
